
server:
  port: 9090
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: Shoxruh0912
    username: postgres
    url: jdbc:postgresql://localhost:5432/ware_house
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        search:
           backend:
              hosts = elasticsearch.mycompany.com
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect


springdoc:
  swagger-ui:
    path: /swagger-ui
    enabled: true
  api-docs:
    path: /api/docs
api:
  info:
    title: Review Service API
    description: API to fetch review details for product
    version: 1.0.0
    terms-of-service: http://boom.com/terms/
    contact:
      name: Review Service API Team
      email: apiteam@example.com
      url: http://boom.com/team
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html

service:
  prop:
    protocol: http
    ip: localhost
    port: 9090
    url: boom.uz
